### ISSUE TITLE
Editor Styles: cover image block doesn't show full-alignment

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/default-small-business-theme#10]
When the cover image block is "full width", it displays as left-aligned and ~60% width in the editor.

<img width="1288" alt="screen shot 2018-11-30 at 5 05 32 pm" src="https://user-images.githubusercontent.com/942359/49317527-de95eb80-f4c2-11e8-9241-332aaa6ef5ee.png">

**Comment by torres126** [comment]
WordPress/gutenberg#11848

**Comment by mendezcode** [comment]
These have been fixed in the rewrite currently being worked on fix/base-editor-styles and when the changes have been reviewed, this issue will be closed.
