### ISSUE TITLE
Editor Styles: core media+text block overflow issues

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/default-small-business-theme#12]
When adding text to the core Media+Text block, the text has a min-width that causes it to not wrap and flow off of the page.

![business-theme-editor](https://user-images.githubusercontent.com/942359/49547547-fb5e6480-f8b0-11e8-8a43-c73f6bda9ae4.png)

**Comment by mendezcode** [comment]
This issue has been fixed as part of the rewrite of the Business editor styles, currently being worked on [fix/base-editor-styles](https://github.com/Automattic/default-small-business-theme/commits/fix/base-editor-styles) and when the changes have been reviewed, this issue will be closed.
