### ISSUE TITLE
Editor Styles: block boundaries overlap

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/default-small-business-theme#13]
When using the Gutenberg editor with the Business theme, block boundaries overlap each other, making some blocks (especially wrapper blocks like columns) almost impossible to select.

![business-theme-editor](https://user-images.githubusercontent.com/942359/49550751-ac1d3180-f8ba-11e8-8867-4a3f79f71a60.png)

**Comment by mendezcode** [comment]
This issue has been fixed as part of the rewrite of the Business editor styles, currently being worked on [fix/base-editor-styles](https://github.com/Automattic/default-small-business-theme/commits/fix/base-editor-styles) and when the changes have been reviewed, this issue will be closed.
