### ISSUE TITLE
Editor Styles: font size inside nested elements is too small/not accurate

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/default-small-business-theme#14]
When using the Gutenberg editor and Business theme, text inserted into a wrapper component (i.e. columns) is rendered very small and doesn't match the front-end.

![business-theme-editor](https://user-images.githubusercontent.com/942359/49551055-bdb30900-f8bb-11e8-934d-7a53144cac56.png)

**Comment by mendezcode** [comment]
This issue has been fixed as part of the rewrite of the Business editor styles, currently being worked on [fix/base-editor-styles](https://github.com/Automattic/default-small-business-theme/commits/fix/base-editor-styles) and when the changes have been reviewed, this issue will be closed.
