### ISSUE TITLE
Editor Styles: media+text block padding doesn't match front-end

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/default-small-business-theme#15]
When using the Gutenberg editor and Business theme, the whitespace between image and content doesn't match the front-end. This doesn't exist in Radcliffe, with the same content.

**Editor:**
![business-theme-editor](https://user-images.githubusercontent.com/942359/49551203-5ea1c400-f8bc-11e8-8c12-8e3bdfc540f5.png)

**Front-end:**
![business-theme-frontend](https://user-images.githubusercontent.com/942359/49551251-914bbc80-f8bc-11e8-882d-321b73146792.png)

**Comment by mendezcode** [comment]
This issue has been fixed as part of the rewrite of the Business editor styles, currently being worked on [fix/base-editor-styles](https://github.com/Automattic/default-small-business-theme/commits/fix/base-editor-styles) and when the changes have been reviewed, this issue will be closed.
