### ISSUE TITLE
Add Option to Hide Home Page/Front Page Title

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/default-small-business-theme#6]
After talking to @ianstewart, @fditrapani, @michaeldcain and @davemart-in, we decided we needed the flexibility hide the home page/front page title on a site. This allows the customer more design flexibility.

We'd want to do this in a theme option, but we could put that setting in the Homepage Settings of the Customizer. This title would just be hidden off screen visually so as to not impact SEO or accessibility.

If we do that, there is potentially some CSS we'd want to adjust. See this video from @davemart-in: https://cl.ly/07f9d07ad8f4

cc: @alaczek

**Comment by crunnells** [comment]
This was fixed in 070763b8caaaf7e5a9d3aaaf66699319f157edf3
